sudo: true
language: cpp
compiler:
    - g++
    - clang
os:
    - linux
    - osx
    
install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then  sudo apt-get install -qq cmake; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export CXX="g++-4.8"; fi
  
  
script:
    - cmake --version
    - cmake .
    - make